### ISSUE TITLE
Make events fire asynchronously and dispatched during request animation frame or setImmediate ~34

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-event#11]
## Proposal

This proposal seeks to do away with the need for `canBatch.start()` and `canBatch.stop()` by making batching the default.  

At the end of a request animation frame, all events would be dispatched, and live bound templates updated.

## Why Now?

Because this has to be done during a major release.  If don't do it now, it will be hard or impossible to do before a 4.0.  CanJS's event system is used by everything.

## Benefits

No more calling `canBatch.start()` and `canBatch.stop()`.  This is likely very confusing to users.  We want people to fall into the pit of success.

Things like animations driven by state changes will run more smoothly.

## Drawbacks

- Debugging what mutation caused what even might be more difficult because you can't look up the call stack. This is already difficult with the new batch queuing system.  There is no longer a 1-1 relationship between change and dispatch.  Some work could be done so a trace of an event is available in dev mode.

### Migration

This would break nearly all of CanJS's tests which rely on synchronous events.  For example, a test that renders a template, changes some observable, investigate the updated DOM immediately.

A `event.flush()` can help like:

```js
var frag = template(map);
map.foo = "bar";
event.flush();
frag.firstChild.nodeValue //-> "bar"
```

This will almost certainly break old apps.

A `event.legacy()` which operates the old way would help.

## Alternatives

- Make `can-view-live` where the real async behavior happens.  Flush will be more difficult, but possible.  The benefit here is that the state can change a whole bunch, but the template would wait until its all done. We could then dispatch data events on `setImmediate` and DOM updates on `RAF`.
- We could release 3.0 and immediately set out to release a 4.0 with this change.
- We could have people turn this on.  `event.async()`

## Implementation details

I would probably merge can-event and can-event/batch.

The 1st event dispatched would need to requestAnimationFrame.  This event and all future events until that point would be put in the batch queue similar to how they are done now.

When the requestAnimationFrame is complete, the batch would be stopped similar to what is done now.  That would fire off that batch's events and any other events that were dispatched at this time would also be dispatched immediately (not async because we need computes of computes to update).

OTHER:

 - what if event listeners are removed - we are dispatching the event at a time point, so that's ok.

**Comment by marshallswain** [comment]
@justinmeyer If we think it will take a while, I’m a fan of getting 3.0 out (and a DoneJS release to match it. There are a lot of patch releases not included in the current DoneJS pre-release.) then putting this stuff in 4.0.  This is mostly for my donejs-feathers work.  I think the issue with can-set’s object unions is the only bug preventing it from working really smoothly.

**Comment by justinbmeyer** [comment]
@marshallswain the problem with waiting is that 4.0 might be 2 years from now.  This might take a week or 2.

**Comment by marshallswain** [comment]
Oh.  I thought you were saying that this big feature would basically be 4.0.

**Comment by justinbmeyer** [comment]
@marshallswain Yeah, it could be.  The problem is that we wouldn't really develop 3.0 then.  It would just be a  "touch and go".  We'd release it, but wouldn't really want to actively support it for very long.  This would be a shame because we'd been hoping that 3.0 would be a nice stable core for a long time.

**Comment by marshallswain** [comment]
ahh. yeah.  From a support standpoint that wouldn't be nice for anybody.

**Comment by DesignByOnyx** [comment]
I'm 100% for this feature coming sooner than later, but I am also with Marshall in that if it delays the release any further than I'd vote for this:
> We could have people turn this on. `event.async()`

**Comment by justinbmeyer** [comment]
@DesignByOnyx That would still introduce a delay because we'd have to make sure can-event can support `event.async()`.  This means basically making this work.

**Comment by phillipskevin** [comment]
I don't like the idea of saying we're going to do this in 4.0. Now that we've broken everything into small repos, having to make a major version bump across all projects at the same time would be a huge pain for users (and to support, etc).

I also like the idea of using requestAnimationFrame in `can-view-live` to auto-batch DOM updates. But I think it would still be confusing to explain to users that they still need to manually batch other non-DOM updates.

I think it's worth doing the full proposal now.

**Comment by pYr0x** [comment]
sorry that i got lost over the meetup. my internet connect was bad.

i agree to do this now. 
test will growing and the work will not getting less in the future.

i also think we should move to `mocha`.

i think it will be worth doing all this

**Comment by justinbmeyer** [comment]
@pYr0x on the mocha thing ... that can at least be done individually in each repo.

**Comment by BigAB** [comment]
*Question:* with events firing asynchronously would derived values, say on a map property getter, also only update asynchronously?

I think a user who would be confused by `batch.start()` and `batch.stop()` would be **far** more confused that after setting name, last name still returns the old value.

**Comment by justinbmeyer** [comment]
@BigAB yes.  This is like promises and streams.  They don't update immediately.  Promises don't have synchronous value retrieval.  

Generally speaking, you shouldn't do that sort of thing in an application.

**Comment by justinbmeyer** [comment]
@BigAB it might be possible to make reading computes call a batchEnd.  This is already in place actually.  If there are no updates, the cached value is returned.  If there are events, they could be dispatched at that time, providing the updated value.

**Comment by BigAB** [comment]
I am not sure what you mean by "you shouldn't do that sort of thing in an application".

I imagine this:
```javascript
const Person = DefineMap.extend({
  firstName: 'string',
  lastName: 'string',
  fullName: {
    get() { return `${ this.firstName } ${ this.lastName }`; }
  }
});

let p = new Person({ firstName: 'Justin', lastName: 'Meyer' });
p.firstName = 'Ramiya';
console.log( p.fullName ) // Justin Meyer   **CanJS Wat?**
```

...only multiplied by the complexity of an actual application.

The synchronous updates of our observables is a benefit, it simplifies the mental concept.
Stroll old angular StackOverflow question and see how much confusion can be caused when models don't update when you think they will.

Making the events fire asynchronously is a *performance enhancement* and should be handled accordingly: i.e. when a performance bottle neck is discovered, give an option to relive that bottleneck (currently handled by adding `batch.start()` and `batch.stop()`.

If this is a DOM concern, perhaps solve it in the stache layer not the Observables.

*caveat* if the whole...
> make reading computes call a batchEnd.

...solves that problem, I would change my tune.

**Comment by BigAB** [comment]
Unless I am missing something, I think we would be making our observables far less predictable which *I have no doubt* will cause users including us to introduce strange and hard to track down bugs ("Grrrr, why is this number not updating!!??") for only the benefit of removing `batch.start()` and `batch.stop()`? 

This seems like a bad idea.

**Comment by justinbmeyer** [comment]
They would be approximately as unpredictable as they are now. Event dispatching order would be the same. 

We'd be helping people do the right thing. Every other framework pretty much works this way. 

ES observables would also be fired at end of turn.

**Comment by justinbmeyer** [comment]
Another issue that we can work around ... binding and dispatching order.

Say there's code like:

```js
obj.dispatch("foo");
obj.dispatch("foo");
obj.on("foo", handler);
```

In a naive implementation, `handler` will be called twice.  We can fix this by making `.on` register in the future, after the "foo" events have been dispatched.

**Comment by justinbmeyer** [comment]
Currently, I'm creating a `can-event/async/async` module that exports a `sync()` and `async()` method.  Calling `async()` overwrites `can-event.dispatch` to dispatch all events async.  

It also changes `addEventListener` and `removeEventListener` to also happen in the batch.  This is so you can't get events dispatched before binding.

My hope is that this might speed up initial render times as all the binding work can happen after the initial render.

**Comment by justinbmeyer** [comment]
Closing for now.  It's not fully implemented, but it's possible.
