### ISSUE TITLE
Dispatch should warn if called with too many arguments or not an array.

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/can-event#29]
I have lost time on this several times because there is an API that I keep expecting. When dispatching an event, there is always data that I want to pass along, but that data must be wrapped in an array:

     this.dispatch("some-event", [extraData]);

 However I keep thinking I should be able to:
 
    this.dispatch("some-event", extraData);

Most of the time I have only one object like this, but I would also think the API could handle a spread of arguments:

```js
var extraData = [foo, bar, baz];
this.dispatch("some-event", extraData); // existing api
this.dispatch("some-event", ...extraData); // new api
//=> this.dispatch("some-event", extraData[0], extraData[1], extraData[2]);
```

**Comment by justinbmeyer** [comment]
We used to support this, but it was confusing when people passed arrays.

Closing also because w/ event streams, we really want people doing `dispatch({type: "SOMETHING", .... other data .... });`

**Comment by justinbmeyer** [comment]
I'm opening because we should probably warn people if they pass more than 2 arguments.

**Comment by DesignByOnyx** [comment]
In my situation, it would have been nice to get a warning that the extra data was not an array as my extra data was just disappearing. Maybe if there is only one argument, and it's not an array, maybe auto-convert it?

```
this.dispatch("some-event", extraData);
```
