### ISSUE TITLE
Add support for `.removeEventListener()` and `.removeEventListener(eventName)` ~8

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-event#4]
From: https://github.com/canjs/canjs/issues/1870

Add the jquery-like ability to unbind to all even handlers of a certain type:

```
foo.unbind("bar")
```

Or unbind all event handlerS:

```
foo.unbind();
```

Make sure this works with lifecycle events.

I think stopListening already does something like this.  There's probably code to absorb.

**Comment by justinbmeyer** [comment]
Related pull request: https://github.com/canjs/canjs/pull/1935

**Comment by justinbmeyer** [comment]
Perhaps `.on` and `.off` might do this.  But I don't think `.addEventListener` should.  We need `.addEventListener` to be super fast.

**Comment by justinbmeyer** [comment]
@mjstahl 's solution won't work.  We have to loop through the events and detach each one so counters are kept.

**Comment by justinbmeyer** [comment]
I think we should have `<can-component>` call `.off()` and possibly `.stopListening()` on its view model.  This will mean we can allow VMs like:

```js
var PlaylistVM = can.DefineMap.extend("PlaylistVM",{
  init: function(){
    var self = this;
    
    self.on("googleAuth", function(ev, googleAuth){
      self.signedIn = googleAuth.isSignedIn.get();
      googleAuth.isSignedIn.listen(function(isSignedIn) {
        self.signedIn = isSignedIn;
      });
    });
    
    self.on("createPlaylistPromise", function(ev, promise){
      if(promise) {
        promise.then(function(){
          self.playlistVideos = [];
          self.createPlaylistPromise = null;
        });
      }
    })
  },
  appLoadedPromise: {
    value: function(){
      return appLoadedPromise;
    }
  },
```

**Comment by bgando** [comment]
@justinbmeyer - Here is an example of how it works now:
```js
var assign = require("can-util/js/assign/assign");
var canEvent = require("can-event");

function Thing(){ ... }
assign(Thing.prototype, canEvent);

var thing = new Thing();
thing.addEventListener("prop", function(){ ... });
thing.removeEventListener("prop", function{ ... });
```
What is the difference in behavior or syntax you are looking for? What would the following methods do? How would this differ (if at all) if Thing was a `can-component`?
```js
thing.off();
thing.stopListening();
```
