### ISSUE TITLE
Support setup/teardown per event type

### ISSUE THREAD

**Issue by rjgotten** [canjs/can-event#8]
Currently `_eventSetup` and `_eventTeardown` are run when the first handler of any event type is added and the last handler of all event types is removed.

It could be useful to complement this with setup and teardown methods that run when the first event of a specific type is added and the last event of that same type is removed.

**Comment by justinbmeyer** [comment]
I think that feature might be needed in another module.  I'm hesitant to add any additional complexity to CanJS's event system b/c it's arguably it's biggest performance bottleneck.  Something like this should be opt-in.

**Comment by justinbmeyer** [comment]
Many of the events in can-util do this sorta thing already:  https://github.com/canjs/can-util/blob/master/dom/events/make-mutation-event/make-mutation-event.js#L56

Perhaps what's really needed is a way to cache events of a certain type?

**Comment by rjgotten** [comment]
> Perhaps what's really needed is a way to cache events of a certain type?

No. I'd actually use it on `Map` subclasses to listen for certain change events bubbling up on deeper nested maps, which in turn require some logic to run on the top level map, which will conditionally result in dispatching a different type of event.

Specifically: I'm working on a faceted search which is managed by an overarching meta model that has a `state` property which switches between idle; processing in background; and processing in foreground. The latter being 'blocking'. The blocking state is only entered when a facet selection is updated in a manner that could possibly result in narrowing the search result. Blocking the UI is necessary in those cases to prevent 'dead ends' in the search.

The only sane way to model it is to have each facet's map keep track of its selection values and, when it changes in a way that is narrowing, have it bubble up a special "narrow" event. That requires each facet to bind a change event on itself to listen for changes in its own selection. Naturally, you only want to do that when something else is actively listening for this "narrow" event.

**Comment by justinbmeyer** [comment]
@rjgotten yeah, but you can set this up yourself if you can _catch_ a certain type of event, just like we are doing with mutation events.  One will have to manage their own counter and behavior, but this would at least make it possible.

Btw, "change" events are not in DefineMap.  Maybe you could elaborate more on why they are necessary for your use case?  Perhaps with a quick mockup of what you are describing?

**Comment by rjgotten** [comment]
> Maybe you could elaborate more on why they are necessary for your use case?

Because "change" events are used as the basis for the custom "narrow" event I described. The required control flow cannot be modeled based on computes and value changes.

**Comment by justinbmeyer** [comment]
Would: https://github.com/canjs/can-define/issues/15 solve your problem?

**Comment by rjgotten** [comment]
Hmm... if having a reactive stream can allow for the previous computed value to remain accessible in parallel with the new value, then yes: that would do the trick.

**Comment by rjgotten** [comment]
@justinbmeyer 
Just chiming back in to mention that I've hooked BaconJS into my project and indeed; reactive streams are working *beautifully* to solve not just this particular widen/narrow custom event issue, but potentially several others as well.

I guess the feature request for event-specific setup/teardown can be ... torn down now?

**Comment by justinbmeyer** [comment]
@rjgotten you might want to check out: https://github.com/canjs/can-compute-stream

**Comment by rjgotten** [comment]
@justinbmeyer 
Nice. My own solution does something similar with compute -> stream -> compute conversion.
